### ISSUE TITLE
nodes construction when utilizing two adatas

### ISSUE THREAD

**Issue by ThisisHubert** [JonETJakobsson/scConnect#2]
![Screenshot 2021-12-16 at 0 07 33](https://user-images.githubusercontent.com/45662327/146211526-a944eda2-4c8d-4ace-8dcb-80efefcfd092.png)

I have a question about the node construction 
`nodes = cn.connect.nodes(adata_tissue)
`
when we want to connect two adatas (adata_tissue_A & adata_tissue_B), should I merge the these two first 
(`adata_tissue = adata_tissue_A.concatenate(adata_tissue_B)`)?

Thank you.

**Comment by JonETJakobsson** [comment]
Hi!

`cn.connect.nodes()` accepts a list of adatas, so you could write `nodes = cn.connect.nodes([adata_tissue_A, adata_tissue_B])`

This would find all nodes in the two datasets. Note however that the names must be unique, otherwise cell type "A" in tissue A would be merge with cell type "A" in tissue B.

Hope that helps!

Kindly,
Jon
